[schedule]
check_interval_minutes = 45
active_hours_start = "09:00"
active_hours_end = "23:40"
active_days = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
jitter_percent = 30

[browser]
headless = true
browser_type = "chromium"
locale = "pl-PL"
timezone = "Europe/Warsaw"
# user_data_dir = "/home/user/.config/google-chrome/Default"

[notifications]
cooldown_minutes = 120
apprise_urls = [
#    "tgram://BOT_TOKEN/CHAT_ID",
     "mailto://user:app_pass@gmail.com?to=me@gmail.com",
    # "pover://USER_KEY@APP_TOKEN",
]

[[doctors]]
name = "Dr Jan Kowalski"
url = "https://www.znanylekarz.pl/jan-kowalski/kardiolog/warszawa"
speciality = "Kardiologia"
check_priority = 1
# earlier_than = "2026-05-01"  # notify only if slot is before this date (YYYY-MM-DD)

[[doctors]]
name = "Dr Anna Nowak"
url = "https://www.znanylekarz.pl/anna-nowak/dermatolog/krakow"
speciality = "Dermatologia"
check_priority = 2
earlier_than = "2026-06-30"  # notify only if slot is before 2026-06-30
